import { ArtEvent } from "./types";

export const mockEvents: ArtEvent[] = [
  {
    id: "1",
    titre: "Vernissage — Lignes de fuite",
    description:
      "Exposition collective autour du dessin contemporain, avec cinq artistes émergents du 20e arrondissement.",
    type: "vernissage",
    discipline: "Peinture",
    ville: "Paris",
    quartier: "Belleville",
    date: "2026-07-24T19:00:00",
    lieu: "Galerie du Marais Est",
  },
  {
    id: "2",
    titre: "Open call — Résidence d'été",
    description:
      "Appel à candidatures pour une résidence de 6 semaines dans un atelier partagé, toutes disciplines.",
    type: "open_call",
    discipline: "Multidisciplinaire",
    ville: "Paris",
    quartier: "Montreuil",
    date: "2026-08-01T00:00:00",
    lieu: "Candidature en ligne",
  },
  {
    id: "3",
    titre: "Workshop — Taille directe sur pierre",
    description:
      "Initiation à la sculpture sur pierre calcaire, matériel fourni, places limitées à 8 participants.",
    type: "workshop",
    discipline: "Sculpture",
    ville: "Paris",
    quartier: "Pantin",
    date: "2026-07-27T10:00:00",
    lieu: "Atelier des Grands Voisins",
  },
  {
    id: "4",
    titre: "Annonce — Chevalet à donner",
    description: "Chevalet en bois massif, bon état, à venir chercher sur place.",
    type: "annonce",
    sousType: "materiel",
    discipline: "Peinture",
    ville: "Paris",
    quartier: "Belleville",
    date: "2026-07-20T00:00:00",
    lieu: "Belleville",
  },
  {
    id: "5",
    titre: "Performance — Corps et mémoire",
    description:
      "Performance immersive d'une heure explorant la mémoire corporelle, suivie d'un échange avec l'artiste.",
    type: "expo",
    discipline: "Performance",
    ville: "Paris",
    quartier: "Bastille",
    date: "2026-08-05T20:30:00",
    lieu: "La Compagnie",
  },
  {
    id: "6",
    titre: "Vernissage — Σκιές (Ombres)",
    description:
      "Exposition solo explorant la lumière et l'ombre à travers la peinture à l'huile.",
    type: "vernissage",
    discipline: "Peinture",
    ville: "Athènes",
    quartier: "Psyrri",
    date: "2026-07-23T19:30:00",
    lieu: "Galerie Kolonaki Sud",
  },
  {
    id: "7",
    titre: "Atelier partagé — Places disponibles",
    description:
      "Deux places libres dans un atelier de sculpture partagé, accès 24/7, quartier calme.",
    type: "annonce",
    sousType: "atelier",
    discipline: "Sculpture",
    ville: "Athènes",
    quartier: "Metaxourgeio",
    date: "2026-07-19T00:00:00",
    lieu: "Metaxourgeio",
  },
  {
    id: "8",
    titre: "Expo collective — Nouvelle scène athénienne",
    description:
      "Douze artistes de la scène émergente athénienne, toutes disciplines confondues.",
    type: "expo",
    discipline: "Multidisciplinaire",
    ville: "Athènes",
    quartier: "Exarcheia",
    date: "2026-08-10T18:00:00",
    lieu: "Espace Exarcheia",
  },
  {
    id: "9",
    titre: "Workshop — Écriture scénique et performance",
    description:
      "Deux jours d'atelier autour de l'écriture pour la performance, ouvert aux débutants.",
    type: "workshop",
    discipline: "Performance",
    ville: "Athènes",
    quartier: "Koukaki",
    date: "2026-08-02T09:00:00",
    lieu: "Studio Koukaki",
  },
  {
    id: "10",
    titre: "Open call — Biennale des matériaux recyclés",
    description:
      "Appel à projets pour une exposition sur l'art fait de matériaux recyclés, dépôt de dossier avant le 15 août.",
    type: "open_call",
    discipline: "Sculpture",
    ville: "Athènes",
    quartier: "Gazi",
    date: "2026-08-15T00:00:00",
    lieu: "Candidature en ligne",
  },
  {
    id: "11",
    titre: "Annonce — Recherche modèle vivant",
    description:
      "Recherche modèle pour séances de dessin hebdomadaires, indemnisation prévue.",
    type: "annonce",
    sousType: "oeuvre",
    discipline: "Peinture",
    ville: "Paris",
    quartier: "Belleville",
    date: "2026-07-21T00:00:00",
    lieu: "Atelier Belleville",
  },
  {
    id: "12",
    titre: "Vernissage — Matière première",
    description:
      "Exposition de sculptures en céramique brute, sans cuisson, sur le thème du temps.",
    type: "vernissage",
    discipline: "Sculpture",
    ville: "Paris",
    quartier: "Montreuil",
    date: "2026-07-31T19:00:00",
    lieu: "Fabrique Montreuil",
  },
];
